apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    component: backend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  type: NodePort




















# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: backend
#   name: backend-service
# spec:
#   ports:
#   - port: 8000
#     targetPort: 8000
#   selector:
#     app: backend
# status:
#   loadBalancer: {}