apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    appdb: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: mongodb
  template:
    metadata:
      labels:
        appdb: mongodb
    spec:
      containers:
        - name: mongodb-deploy
          image: mongo
          ports:
            - containerPort: 27017